---
- name: Install java and net-tools
  hosts: ec2-instance-ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8 and net-tools, and acl
      apt:
        pkg:
          - openjdk-8-jre-headless
          - net-tools
          - acl

- name: Download, unpack Nexus installer and rename it
  hosts: ec2-instance-ubuntu
  become: yes
  become_user: root
  tasks:
    - name: check nexus folder status
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - name: Rename the nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create a new user to own the nexus folders
  hosts: ec2-instance-ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Ensure the group exists
      group:
        name: nexus
        state: present
    - name: Create a new user and assign the user to a group
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folders
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folders
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: ec2-instance-ubuntu
  become: yes
  # become_method: enable
  become_user: nexus
  tasks:
    # Method 1: using blockinfile module
    - name: Set run_as_user nexus
      blockinfile:
        path: /opt/nexus/bin/nexus.rc
        block: |
          run_as_user="nexus"

    # method 2: using lineinfile module
    # - name: Set run_as_user nexus
    #   lineinfile:
    #     path: /opt/nexus/bin/nexus.rc
    #     regexp: '^#run_as_user=""'
    #     line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Verifying nexus running
  hosts: ec2-instance-ubuntu
  become: yes
  become_user: nexus
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status}}
    - name: Wait for 1 minute
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -nplt
      register: app_status
    - debug: msg={{app_status}}
